In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import librosa
import soundfile
import torch
import torchaudio
from torchaudio import transforms as T
import librosa
import soundfile

import sys
import os
sys.path.append('./dataset/cats_dogs_dataset')
import utils
import myutils

print(torch.cuda.is_available())

loaded train_cat with 942.0454375 sec of audio
loaded train_dog with 317.2408125 sec of audio
loaded test_cat with 381.8525 sec of audio
loaded test_dog with 281.1975 sec of audio
True

In [2]:
df = pd.read_csv(f'dataset/cats_dogs_dataset/train_test_split.csv', index_col=0)
df.head()

      test_cat            test_dog    train_cat           train_dog
0   cat_22.wav  dog_barking_97.wav   cat_99.wav  dog_barking_33.wav
1  cat_116.wav   dog_barking_0.wav   cat_54.wav  dog_barking_86.wav
2  cat_155.wav  dog_barking_93.wav   cat_34.wav  dog_barking_45.wav
3   cat_58.wav  dog_barking_10.wav  cat_132.wav  dog_barking_76.wav
4   cat_77.wav  dog_barking_26.wav  cat_124.wav   dog_barking_4.wav

In [3]:
df = df.dropna()
df.isna().sum()

test_cat     0
test_dog     0
train_cat    0
train_dog    0
dtype: int64

In [6]:
audio_dir = 'dataset/cats_dogs_dataset/cats_dogs/'
extracted = {}

for columns in ['test_cat', 'test_dog', 'train_cat', 'train_dog']:

    rows = []

    for value in df[columns]:
        path = os.path.join(audio_dir, value)

        extracted_feat = myutils.feature_extraction(path)
        mean_mfcc = extracted_feat.pop('mean_mfcc')
        std_mfcc = extracted_feat.pop('std_mfcc')
        for i, v in enumerate(mean_mfcc):
            extracted_feat[f"mfcc_mean_{i+1}"] = v

        for i, v in enumerate(std_mfcc):
            extracted_feat[f"mfcc_std_{i+1}"] = v
        
        rows.append(extracted_feat)

    extracted[columns] = pd.DataFrame(rows)

In [11]:
extracted['test_cat'].head()

,mean,std,max,min,median,rms,zcr,centroid_mean,centroid_std,centroid_min,...,mfcc_std_4,mfcc_std_5,mfcc_std_6,mfcc_std_7,mfcc_std_8,mfcc_std_9,mfcc_std_10,mfcc_std_11,mfcc_std_12,mfcc_std_13
0,-0.000016,0.011879,0.110180,-0.109939,0.000008,0.011879,0.142651,1464.566247,480.531969,954.926290,...,13.744926,12.523030,10.164818,9.699970,9.146374,7.881964,6.759873,7.001926,6.516466,11.956180
1,-0.000024,0.108300,1.002346,-1.008581,0.000002,0.108300,0.186925,1771.869641,367.704205,485.782692,...,19.294889,7.089887,14.912495,11.365731,5.317187,9.384636,7.245938,4.460561,6.297989,6.958369
2,-0.000165,0.180907,0.879862,-1.026622,0.000639,0.180907,0.233267,1970.451544,232.449470,1682.442810,...,16.961130,7.720398,11.911196,13.629316,9.824914,7.629483,15.899711,10.822435,8.214504,13.608309
3,-0.000018,0.061967,0.646913,-0.633030,-0.000056,0.061967,0.306471,2272.111828,256.600595,1187.426101,...,10.053801,9.177458,8.716433,8.539826,8.425459,9.645827,7.400805,7.459779,10.372723,9.861313
4,-0.000128,0.181112,1.012849,-0.866000,-0.001748,0.181113,0.097929,1115.022040,628.514559,160.705812,...,22.625322,27.430752,11.231981,12.947573,12.660388,19.912170,15.812548,15.578539,16.288433,15.732352